### ISSUE TITLE
MUIM_TheBarNoNotifySetAttr for mutual excluding buttons

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/thebar#3]
Trying to set MUIV_TheBar_Attr_Selected state using MUIM_TheBar_NoNotifySetAttr on a button that is part of a mutual exclude group doesn't seem to work. I still get a notification on MUIA_Selected. As a workaround, I've tried to use MUIA_TheBar_Active with MUIA_NoNotify but that didn't do the trick either.

**Comment by tboeckel** [comment]
Test archives sent privately as github refuses to accept my .zip files and suggests to use .zip files instead?!?

**Comment by jens-maus** [comment]
[thebar_test.zip](https://github.com/amiga-mui/thebar/files/241922/thebar_test.zip)

**Comment by jens-maus** [comment]
works here, as you can see ;)
