### ISSUE TITLE
Add support for ToolBar MCC class

### ISSUE THREAD

**Issue by samo79** [amiga-mui/thebar#7]
TheBar MCC could provide a sort of internal wrapper in order to support the older ToolBar MCC class and functionalities

Original report here:
https://muidev.de/ticket/454

**Comment by tboeckel** [comment]
Can you provide some examples of applications which rely upon Toolbar.mcc?
Please note, a wrapper class can only be an approximation of the real class provided the new base class offers the same features as the original class. So it might be possible that a wrapper class might be incomplete or might react differently than the original class.

**Comment by samo79** [comment]
Sure, some software that quickly comes in my mind are: 

AmiGift 2.1
MagicReader 0.46
AutoDocArt 1.031
eNote 1.6
AminetIdx 1.3

And various others.. all of them could be found on Aminet

About the wrapper: 
Yes I figured it wouldn't be easy...  for this reason perhaps it would probably more logical (and easier) to just integrate the current Toolbar class into the MUI archive rather than breaking our head into writing a wrapper from scratch which we should then betatest aniway... :-)

**Comment by tboeckel** [comment]
We already have a working toolbar class. I am not going to implement yet another one. A wrapper is much easier to do than having to deal with all the low level details like loading images, etc.

**Comment by tboeckel** [comment]
[Toolbar_26.1_os3.zip](https://github.com/amiga-mui/thebar/files/5416896/Toolbar_26.1_os3.zip)
[Toolbar_26.1_os4.zip](https://github.com/amiga-mui/thebar/files/5416897/Toolbar_26.1_os4.zip) 
Test binaries for AmigaOS3 and AmigaOS4

**Comment by samo79** [comment]
Indeed, for this reason I imagined that it would be better to integrate the class as it was, rather than making a wrapper :-)
Aniway as it seems you did that already i will test it, thanks a lot Thore :-)

**Comment by samo79** [comment]
Ok i've started some test, tried an heavy one (AmiGift 2.0) and all goes well.
Atleast no issue for now.. :-)
Will test some more programs in the coming days/weeks

Just a question, maybe we will need also the related Toolbar.mcp ?
If not from where we can eventually configure the things

**Comment by tboeckel** [comment]
Well, since the new Toolbar.mcc is just a wrapper around TheBar.mcc all the configuration is of course done with TheBar.mcp.

**Comment by samo79** [comment]
Ah ok, so i presume the real "compatibility test" to do will be there
